eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  environment: dev
  instance:
    hostname: eureka-service
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5